"""cadastros: bases, veiculos, motoristas e clientes

Revision ID: 3399c3f2c524
Revises: 3cb2976c276c
Create Date: 2026-09-19 01:51:54.422697
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3399c3f2c524'
down_revision: str | None = '3cb2976c276c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bases',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geocode_status', sa.String(length=20), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.Column('geocode_precision', sa.String(length=20), nullable=True),
    sa.Column('geocode_provider', sa.String(length=40), nullable=True),
    sa.Column('geocode_error', sa.String(length=255), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("geocode_precision IS NULL OR geocode_precision IN ('EXATO', 'RUA', 'BAIRRO', 'CIDADE')", name=op.f('ck_bases_geocode_precisao_valida')),
    sa.CheckConstraint("geocode_status IN ('PENDENTE', 'OK', 'AMBIGUO', 'FALHOU', 'MANUAL')", name=op.f('ck_bases_geocode_status_valido')),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name=op.f('ck_bases_coordenada_completa')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_bases_latitude_valida')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_bases_longitude_valida')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bases')),
    comment='Pontos de partida e retorno das rotas.'
    )
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geocode_status', sa.String(length=20), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.Column('geocode_precision', sa.String(length=20), nullable=True),
    sa.Column('geocode_provider', sa.String(length=40), nullable=True),
    sa.Column('geocode_error', sa.String(length=255), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("geocode_precision IS NULL OR geocode_precision IN ('EXATO', 'RUA', 'BAIRRO', 'CIDADE')", name=op.f('ck_customers_geocode_precisao_valida')),
    sa.CheckConstraint("geocode_status IN ('PENDENTE', 'OK', 'AMBIGUO', 'FALHOU', 'MANUAL')", name=op.f('ck_customers_geocode_status_valido')),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name=op.f('ck_customers_coordenada_completa')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_customers_latitude_valida')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_customers_longitude_valida')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    comment='Clientes que recebem entregas.'
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index('uq_customers_document', 'customers', ['document'], unique=True, postgresql_where=sa.text('document IS NOT NULL'))
    op.create_table('vehicles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('capacity_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacity_volume_m3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('capacity_length_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_stops', sa.Integer(), nullable=True),
    sa.Column('crew_size', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_length_m IS NULL OR capacity_length_m > 0', name=op.f('ck_vehicles_comprimento_positivo')),
    sa.CheckConstraint('capacity_volume_m3 IS NULL OR capacity_volume_m3 > 0', name=op.f('ck_vehicles_volume_positivo')),
    sa.CheckConstraint('capacity_weight_kg IS NULL OR capacity_weight_kg > 0', name=op.f('ck_vehicles_peso_positivo')),
    sa.CheckConstraint('crew_size >= 1', name=op.f('ck_vehicles_equipe_minima')),
    sa.CheckConstraint('max_stops IS NULL OR max_stops > 0', name=op.f('ck_vehicles_paradas_positivas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    comment='Frota disponivel para as rotas.'
    )
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('license_number', sa.String(length=20), nullable=True),
    sa.Column('license_expires_at', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drivers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_drivers_user_id')),
    comment='Motoristas que executam as rotas.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('uq_customers_document', table_name='customers', postgresql_where=sa.text('document IS NOT NULL'))
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('bases')
    # ### end Alembic commands ###
