"""estrutura inicial: usuarios e configuracao da empresa

Revision ID: 3cb2976c276c
Revises: 
Create Date: 2026-09-19 00:20:33.926779
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3cb2976c276c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'America/Campo_Grande'"), nullable=False),
    sa.Column('default_stop_service_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_stop_service_minutes > 0', name=op.f('ck_company_settings_tempo_parada_positivo')),
    sa.CheckConstraint('id = 1', name=op.f('ck_company_settings_linha_unica')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_settings')),
    comment='Dados e preferencias da empresa. Sempre uma unica linha.'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'MOTORISTA')", name=op.f('ck_users_role_valido')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_minusculo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='Usuarios que autenticam no sistema.'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
