"""posicoes do veiculo durante a rota

Revision ID: 3e1526700087
Revises: a8726fa2a415
Create Date: 2026-09-21 16:12:45.957100
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (usado por colunas JSONB)

revision: str = '3e1526700087'
down_revision: str | None = 'a8726fa2a415'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_positions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('accuracy_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('speed_mps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading_deg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy_m IS NULL OR accuracy_m >= 0', name=op.f('ck_route_positions_precisao_valida')),
    sa.CheckConstraint('heading_deg IS NULL OR (heading_deg >= 0 AND heading_deg < 360)', name=op.f('ck_route_positions_direcao_valida')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_route_positions_latitude_valida')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_route_positions_longitude_valida')),
    sa.CheckConstraint('speed_mps IS NULL OR speed_mps >= 0', name=op.f('ck_route_positions_velocidade_valida')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_positions_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_positions')),
    comment='Rastro do GPS do motorista durante a execucao da rota.'
    )
    op.create_index('ix_route_positions_rota_hora', 'route_positions', ['route_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_route_positions_rota_hora', table_name='route_positions')
    op.drop_table('route_positions')
    # ### end Alembic commands ###
