"""registro da limpeza automatica

Revision ID: 76eabe105652
Revises: ef93295ac975
Create Date: 2026-09-22 10:16:49.126413
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (usado por colunas JSONB)

revision: str = '76eabe105652'
down_revision: str | None = 'ef93295ac975'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('terminada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('erro', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_maintenance_runs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_runs')),
    comment='Execucoes da limpeza automatica de dados antigos.'
    )
    op.create_index('ix_maintenance_runs_inicio', 'maintenance_runs', ['iniciada_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maintenance_runs_inicio', table_name='maintenance_runs')
    op.drop_table('maintenance_runs')
    # ### end Alembic commands ###
