"""transito no planejamento

Cache dos trechos medidos no Google e a nova fonte de matriz do plano,
GOOGLE_TRANSITO. A restricao da fonte e refeita a mao: o autogenerate nao
enxerga mudanca dentro de CHECK.

Revision ID: a371780e4bc8
Revises: 76eabe105652
Create Date: 2026-09-22 10:39:44.695355
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (usado por colunas JSONB)

revision: str = 'a371780e4bc8'
down_revision: str | None = '76eabe105652'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trafego_trechos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('origem', sa.String(length=24), nullable=False),
    sa.Column('destino', sa.String(length=24), nullable=False),
    sa.Column('partida', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracao_s', sa.Integer(), nullable=False),
    sa.Column('distancia_m', sa.Integer(), nullable=False),
    sa.Column('consultado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trafego_trechos')),
    comment='Tempo com transito entre dois pontos, por hora de partida.'
    )
    op.create_index('ix_trafego_partida', 'trafego_trechos', ['partida'], unique=False)
    op.create_index('ux_trafego_trecho', 'trafego_trechos', ['origem', 'destino', 'partida'], unique=True)
    # ### end Alembic commands ###
    op.drop_constraint('fonte_matriz_valida', 'route_plans', type_='check')
    op.create_check_constraint(
        'fonte_matriz_valida', 'route_plans',
        "matrix_source IN ('OSRM', 'HAVERSINE', 'GOOGLE_TRANSITO')",
    )


def downgrade() -> None:
    op.drop_constraint('fonte_matriz_valida', 'route_plans', type_='check')
    op.create_check_constraint(
        'fonte_matriz_valida', 'route_plans', "matrix_source IN ('OSRM', 'HAVERSINE')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_trafego_trecho', table_name='trafego_trechos')
    op.drop_index('ix_trafego_partida', table_name='trafego_trechos')
    op.drop_table('trafego_trechos')
    # ### end Alembic commands ###
