"""CEP nas entidades com endereco

Revision ID: a8726fa2a415
Revises: f2fa452246c7
Create Date: 2026-09-19 09:07:17.746235
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (usado por colunas JSONB)

revision: str = 'a8726fa2a415'
down_revision: str | None = 'f2fa452246c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bases', sa.Column('postal_code', sa.String(length=8), nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.String(length=8), nullable=True))
    op.add_column('deliveries', sa.Column('postal_code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'postal_code')
    op.drop_column('customers', 'postal_code')
    op.drop_column('bases', 'postal_code')
    # ### end Alembic commands ###
