"""tentativas de login e eventos de seguranca

Revision ID: ef93295ac975
Revises: 3e1526700087
Create Date: 2026-09-22 09:30:29.231408
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (usado por colunas JSONB)

revision: str = 'ef93295ac975'
down_revision: str | None = '3e1526700087'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_attempts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts')),
    comment='Tentativas de login: base do bloqueio por tentativas e da auditoria.'
    )
    op.create_index('ix_login_attempts_email_hora', 'login_attempts', ['email', 'created_at'], unique=False)
    op.create_index('ix_login_attempts_ip_hora', 'login_attempts', ['ip', 'created_at'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_security_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], name=op.f('fk_security_events_target_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events')),
    comment='Eventos de segurança sobre contas: auditoria.'
    )
    op.create_index('ix_security_events_hora', 'security_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_events_hora', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_login_attempts_ip_hora', table_name='login_attempts')
    op.drop_index('ix_login_attempts_email_hora', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
