"""entregas, rotas, paradas, eventos e cache de geocodificacao

Revision ID: f2fa452246c7
Revises: 3399c3f2c524
Create Date: 2026-09-19 02:14:59.740991
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f2fa452246c7'
down_revision: str | None = '3399c3f2c524'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_address', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('precision', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=400), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('address_hash', name=op.f('pk_geocode_cache')),
    comment='Enderecos ja convertidos em coordenada.'
    )
    op.create_table('deliveries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('order_number', sa.String(length=40), nullable=True),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('recipient_name', sa.String(length=160), nullable=True),
    sa.Column('recipient_phone', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('required_crew', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('service_time_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), server_default=sa.text("'NORMAL'"), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('time_window_start', sa.Time(), nullable=True),
    sa.Column('time_window_end', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geocode_status', sa.String(length=20), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.Column('geocode_precision', sa.String(length=20), nullable=True),
    sa.Column('geocode_provider', sa.String(length=40), nullable=True),
    sa.Column('geocode_error', sa.String(length=255), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("geocode_precision IS NULL OR geocode_precision IN ('EXATO', 'RUA', 'BAIRRO', 'CIDADE')", name=op.f('ck_deliveries_geocode_precisao_valida')),
    sa.CheckConstraint("geocode_status IN ('PENDENTE', 'OK', 'AMBIGUO', 'FALHOU', 'MANUAL')", name=op.f('ck_deliveries_geocode_status_valido')),
    sa.CheckConstraint("priority IN ('BAIXA', 'NORMAL', 'ALTA', 'URGENTE')", name=op.f('ck_deliveries_prioridade_valida')),
    sa.CheckConstraint("status IN ('PENDENTE', 'PLANEJADA', 'EM_ROTA', 'CHEGOU', 'ENTREGUE', 'NAO_ENTREGUE', 'CANCELADA')", name=op.f('ck_deliveries_status_valido')),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name=op.f('ck_deliveries_coordenada_completa')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_deliveries_latitude_valida')),
    sa.CheckConstraint('length_m IS NULL OR length_m >= 0', name=op.f('ck_deliveries_comprimento_nao_negativo')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_deliveries_longitude_valida')),
    sa.CheckConstraint('required_crew >= 1', name=op.f('ck_deliveries_equipe_minima')),
    sa.CheckConstraint('service_time_minutes IS NULL OR service_time_minutes > 0', name=op.f('ck_deliveries_tempo_servico_positivo')),
    sa.CheckConstraint('time_window_start IS NULL OR time_window_end IS NULL OR time_window_start < time_window_end', name=op.f('ck_deliveries_janela_coerente')),
    sa.CheckConstraint('volume_m3 IS NULL OR volume_m3 >= 0', name=op.f('ck_deliveries_volume_nao_negativo')),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg >= 0', name=op.f('ck_deliveries_peso_nao_negativo')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_deliveries_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    comment='Entregas a serem planejadas e executadas.'
    )
    op.create_index(op.f('ix_deliveries_customer_id'), 'deliveries', ['customer_id'], unique=False)
    op.create_index('ix_deliveries_data_status', 'deliveries', ['scheduled_date', 'status'], unique=False)
    op.create_index(op.f('ix_deliveries_order_number'), 'deliveries', ['order_number'], unique=False)
    op.create_index(op.f('ix_deliveries_scheduled_date'), 'deliveries', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_table('route_plans',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('base_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'RASCUNHO'"), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('matrix_source', sa.String(length=20), nullable=False),
    sa.Column('solver', sa.String(length=40), nullable=True),
    sa.Column('solver_status', sa.String(length=30), nullable=True),
    sa.Column('solver_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_distance_m', sa.Integer(), nullable=True),
    sa.Column('total_duration_s', sa.Integer(), nullable=True),
    sa.Column('unassigned', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("matrix_source IN ('OSRM', 'HAVERSINE')", name=op.f('ck_route_plans_fonte_matriz_valida')),
    sa.CheckConstraint("status IN ('RASCUNHO', 'CONFIRMADO', 'DESCARTADO')", name=op.f('ck_route_plans_status_valido')),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], name=op.f('fk_route_plans_base_id_bases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_route_plans_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_plans')),
    comment='Resultado de uma otimizacao, ainda nao confirmado.'
    )
    op.create_index('ix_route_plans_data', 'route_plans', ['date', 'status'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('route_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('base_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'RASCUNHO'"), nullable=False),
    sa.Column('sequence_in_day', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('total_distance_m', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_s', sa.Integer(), nullable=True),
    sa.Column('planned_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_volume_m3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geometry', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('RASCUNHO', 'PLANEJADA', 'INICIADA', 'FINALIZADA', 'CANCELADA')", name=op.f('ck_routes_status_valido')),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], name=op.f('fk_routes_base_id_bases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_routes_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_plan_id'], ['route_plans.id'], name=op.f('fk_routes_route_plan_id_route_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_routes_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    comment='Rota de um veiculo num dia.'
    )
    op.create_index('ix_routes_data_status', 'routes', ['date', 'status'], unique=False)
    op.create_index(op.f('ix_routes_driver_id'), 'routes', ['driver_id'], unique=False)
    op.create_index('uq_routes_driver_iniciada', 'routes', ['driver_id'], unique=True, postgresql_where=sa.text("status = 'INICIADA'"))
    op.create_index('uq_routes_vehicle_iniciada', 'routes', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'INICIADA'"))
    op.create_table('route_stops',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('stop_type', sa.String(length=20), nullable=False),
    sa.Column('trip_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_from_previous_m', sa.Integer(), nullable=True),
    sa.Column('duration_from_previous_s', sa.Integer(), nullable=True),
    sa.Column('service_time_s', sa.Integer(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint("status IN ('PENDENTE', 'CHEGOU', 'CONCLUIDA', 'PULADA')", name=op.f('ck_route_stops_status_valido')),
    sa.CheckConstraint("stop_type IN ('BASE_SAIDA', 'ENTREGA', 'BASE_RECARGA', 'BASE_RETORNO')", name=op.f('ck_route_stops_tipo_valido')),
    sa.CheckConstraint('sequence >= 0', name=op.f('ck_route_stops_sequencia_nao_negativa')),
    sa.CheckConstraint('trip_number >= 1', name=op.f('ck_route_stops_viagem_minima')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_id', 'sequence', deferrable=True, initially='DEFERRED', name='sequencia_unica'),
    comment='Paradas de uma rota, na ordem de execucao.'
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('delivery_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('delivery_id', sa.BigInteger(), nullable=False),
    sa.Column('route_stop_id', sa.BigInteger(), nullable=True),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_delivery_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_delivery_events_delivery_id_deliveries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], name=op.f('fk_delivery_events_route_stop_id_route_stops'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_events')),
    comment='Historico append-only das entregas.'
    )
    op.create_index('ix_delivery_events_entrega', 'delivery_events', ['delivery_id', 'created_at'], unique=False)
    op.create_table('route_stop_deliveries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('route_stop_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_in_stop', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PLANEJADA'"), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=30), nullable=True),
    sa.Column('receiver_name', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint("failure_reason IS NULL OR failure_reason IN ('CLIENTE_AUSENTE', 'ENDERECO_INCORRETO', 'RECUSA', 'ESTABELECIMENTO_FECHADO', 'PROBLEMA_ACESSO', 'AVARIA', 'FALTA_PRODUTO', 'OUTRO')", name=op.f('ck_route_stop_deliveries_motivo_valido')),
    sa.CheckConstraint("status IN ('PENDENTE', 'PLANEJADA', 'EM_ROTA', 'CHEGOU', 'ENTREGUE', 'NAO_ENTREGUE', 'CANCELADA')", name=op.f('ck_route_stop_deliveries_status_valido')),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_route_stop_deliveries_delivery_id_deliveries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], name=op.f('fk_route_stop_deliveries_route_stop_id_route_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stop_deliveries')),
    sa.UniqueConstraint('route_stop_id', 'delivery_id', name='entrega_unica_na_parada'),
    comment='Entregas resolvidas em cada parada.'
    )
    op.create_index(op.f('ix_route_stop_deliveries_delivery_id'), 'route_stop_deliveries', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stop_deliveries_delivery_id'), table_name='route_stop_deliveries')
    op.drop_table('route_stop_deliveries')
    op.drop_index('ix_delivery_events_entrega', table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('uq_routes_vehicle_iniciada', table_name='routes', postgresql_where=sa.text("status = 'INICIADA'"))
    op.drop_index('uq_routes_driver_iniciada', table_name='routes', postgresql_where=sa.text("status = 'INICIADA'"))
    op.drop_index(op.f('ix_routes_driver_id'), table_name='routes')
    op.drop_index('ix_routes_data_status', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_route_plans_data', table_name='route_plans')
    op.drop_table('route_plans')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_scheduled_date'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_order_number'), table_name='deliveries')
    op.drop_index('ix_deliveries_data_status', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_customer_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
